variables:
  APP_CONTAINER_PORT: "80"
  APP_EXPOSED_PORT: "80"

image: docker:latest
services:
  - name: docker:dind
    alias: docker


stages:
  - build
  - Test acceptation
  - Release image
  - Deploy review
  - Stop review
  - Deploy staging
  - Test staging  
  - Deploy prod
  - Test prod


.test_template: &test
  image: alpine
  only:
    - master
  script:
    - apk --no-cache add curl
    - curl "https://$DOMAIN" | grep -i "Dimension"  


docker-build:
  # Use the official docker image.
  stage: build
  script:
    - docker build -t  webpage .
    - docker save webpage > webpage.tar
  artifacts:
    paths:
      - webpage.tar    


test acceptation:
  # Official docker image.
  stage: Test acceptation
  script:
    - docker load < webpage.tar
    - docker run -d -p $APP_CONTAINER_PORT:$APP_EXPOSED_PORT -e PORT=$APP_CONTAINER_PORT --name webapp webpage
    - sleep 5
    - apk --no-cache add curl
    - curl "http://docker:$APP_CONTAINER_PORT" | grep -i "Dimension"


release image:
  stage: Release image
  script:
    - docker load < webpage.tar
    - docker tag webpage "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker tag webpage "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker push "${IMAGE_NAME}:${CI_COMMIT_REF_NAME}"
    - docker push "${IMAGE_NAME}:${CI_COMMIT_SHORT_SHA}"


deploy staging:
  stage: Deploy staging
  environment:
    name: staging
    url: https://eazytraining-staging-9839de32fe85.herokuapp.com
  only:
    - master
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create eazytraining-staging || echo "project already exist"
    - heroku container:push -a eazytraining-staging web
    - heroku container:release -a eazytraining-staging web


deploy prod:
  stage: Deploy prod
  environment:
    name: prod
    url: https://eazytraining-prod-70584e6ff38a.herokuapp.com
  only:
    - master
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create eazytraining-prod  || echo "project already exist"
    - heroku container:push -a eazytraining-prod web
    - heroku container:release -a eazytraining-prod web    


deploy review:
  stage: Deploy review
  only:
    - merge_requests
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku create eazytraining-$CI_COMMIT_REF_NAME  || echo "project already exist"
    - heroku container:push -a eazytraining-$CI_COMMIT_REF_NAME web
    - heroku container:release -a eazytraining-$CI_COMMIT_REF_NAME web
    - REVIEW_ENVIRONMENT_URL=$(heroku info eazytraining-$CI_COMMIT_REF_NAME --json | jq '.app.web_url')
    - echo "REVIEW_ENVIRONMENT_URL=$REVIEW_ENVIRONMENT_URL" >> deploy.env
  artifacts:
    reports:
      dotenv: deploy.env  
  environment:
    name: review/$CI_COMMIT_REF_NAME
    url: $REVIEW_ENVIRONMENT_URL
    on_stop: stop review


stop review:
  stage: Stop review
  variables:
    GIT_STRATEGY: none
  environment:
    name: review/$CI_COMMIT_REF_NAME
    action: stop
  only:
    - merge_requests
  when: manual
  script:
    - apk --no-cache add npm
    - npm install -g heroku
    - heroku container:login
    - heroku apps:destroy -a eazytraining-$CI_COMMIT_REF_NAME -c eazytraining-$CI_COMMIT_REF_NAME


test staging:
  <<: *test
  stage: Test staging
  variables:
    DOMAIN: eazytraining-staging-9839de32fe85.herokuapp.com


test prod:
  <<: *test
  stage: Test prod
  variables:
    DOMAIN: eazytraining-prod-70584e6ff38a.herokuapp.com

